import type {
  AnalyzeResponse,
  DocumentSection,
  DraftSubmissionInput,
  PlanMergeProject,
} from "./types";

export const defaultProject: PlanMergeProject = {
  title: "AI 공동 기획서 병합 도구",
  goal: "여러 사람이 각자 AI로 만든 기획서 초안을 하나의 문서로 병합한다.",
  documentType: "service_plan",
  contextPack:
    "MVP는 2주 안에 만들 수 있어야 한다. 초기에는 텍스트 붙여넣기 기반으로 한다. 최종 기획서뿐 아니라 선택되지 않은 의견과 충돌을 보여준다.",
  forbiddenDirections:
    "초기 MVP에서는 실시간 공동 편집, 팀 초대, Slack/Notion/Google Docs 연동, 결제 기능을 제외한다.",
  outputStyle: "짧고 명확한 서비스 기획서. 섹션별로 선택 이유와 대안을 함께 남긴다.",
};

export const defaultSections: DocumentSection[] = [
  {
    sectionKey: "overview",
    title: "개요",
    description: "서비스의 목적과 핵심 가치",
    sortOrder: 1,
  },
  {
    sectionKey: "problem",
    title: "문제 정의",
    description: "사용자가 겪는 문제와 현재 방식의 한계",
    sortOrder: 2,
  },
  {
    sectionKey: "target_user",
    title: "타깃 사용자",
    description: "초기 사용자의 특성",
    sortOrder: 3,
  },
  {
    sectionKey: "pain_point",
    title: "사용자 Pain Point",
    description: "의견 병합 과정에서 발생하는 불편",
    sortOrder: 4,
  },
  {
    sectionKey: "solution",
    title: "솔루션",
    description: "PlanMerge가 제공하는 해결 방식",
    sortOrder: 5,
  },
  {
    sectionKey: "core_features",
    title: "핵심 기능",
    description: "MVP의 주요 기능",
    sortOrder: 6,
  },
  {
    sectionKey: "mvp_scope",
    title: "MVP 범위",
    description: "처음 만들 범위와 제외할 기능",
    sortOrder: 7,
  },
  {
    sectionKey: "user_flow",
    title: "사용자 플로우",
    description: "사용자가 결과를 얻는 흐름",
    sortOrder: 8,
  },
  {
    sectionKey: "requirements",
    title: "요구사항",
    description: "기능/비기능 요구사항",
    sortOrder: 9,
  },
  {
    sectionKey: "success_metrics",
    title: "성공 지표",
    description: "MVP 검증 기준",
    sortOrder: 10,
  },
  {
    sectionKey: "risks",
    title: "리스크",
    description: "제품, 기술, 운영 리스크",
    sortOrder: 11,
  },
  {
    sectionKey: "open_questions",
    title: "미결정 사항",
    description: "사람이 결정해야 하는 질문",
    sortOrder: 12,
  },
];

export const defaultDrafts: DraftSubmissionInput[] = [
  {
    draftId: "draft_pm",
    authorName: "민수",
    authorRole: "PM",
    aiModel: "ChatGPT",
    taskTitle: "MVP 범위와 문제 정의",
    rawText:
      "여러 사람이 AI로 기획서를 만들면 중복과 충돌이 생긴다. 초기 MVP는 텍스트 붙여넣기와 병합 리포트 생성까지만 포함해야 한다. 사용자는 최종안뿐 아니라 왜 선택됐는지, 어떤 의견이 제외됐는지도 확인해야 한다.",
  },
  {
    draftId: "draft_designer",
    authorName: "지현",
    authorRole: "Designer",
    aiModel: "Claude",
    taskTitle: "협업 흐름과 사용성",
    rawText:
      "사용자는 최종 문서를 읽다가 특정 섹션에 커서를 올리면 다른 의견을 바로 볼 수 있어야 한다. Notion으로 내보내거나 Slack에 공유하면 실제 팀 업무 흐름에 더 가까울 수 있다. 비교는 표보다 먼저 핵심 차이 한 줄이 보여야 한다.",
  },
  {
    draftId: "draft_dev",
    authorName: "도윤",
    authorRole: "Developer",
    aiModel: "Gemini",
    taskTitle: "기술 범위와 리스크",
    rawText:
      "실시간 공동 편집을 넣으면 팀 초대, 권한, 동기화, 충돌 해결까지 필요하다. 2주 MVP에서는 위험하다. OpenAI API는 JSON Schema 기반으로 결과를 고정하고, DB 저장은 나중에 Supabase로 붙이면 된다.",
  },
];

export function createMockAnalysis(input?: Partial<AnalyzeResponse>): AnalyzeResponse {
  const response: AnalyzeResponse = {
    summary: {
      text: "초안들은 AI 기획서 병합이라는 목표에는 일치하지만, 초기 MVP 범위와 외부 연동 포함 여부에서 의견 차이가 있습니다.",
      sectionCount: 12,
      autoSelectedCount: 8,
      needsReviewCount: 4,
      conflictCount: 3,
      overallRiskLevel: "medium",
    },
    finalDocument: {
      title: "PlanMerge MVP 기획서",
      sections: [
        {
          sectionId: "section_overview",
          sectionKey: "overview",
          title: "개요",
          content:
            "PlanMerge는 여러 AI 기획서 초안을 하나의 기획서로 병합하면서, AI가 선택한 아이디어와 선택되지 않은 다른 의견을 섹션별로 추적하는 도구다.",
          sortOrder: 1,
          status: "auto_selected",
          confidence: 0.89,
          conflictLevel: "low",
          alternativeCount: 1,
          conflictCount: 0,
        },
        {
          sectionId: "section_problem",
          sectionKey: "problem",
          title: "문제 정의",
          content:
            "여러 사람이 각자 AI로 초안을 만들면 내용이 빨리 늘어나지만, 중복된 주장과 서로 다른 방향의 제안이 섞여 최종 결정을 내리기 어렵다.",
          sortOrder: 2,
          status: "auto_selected",
          confidence: 0.86,
          conflictLevel: "low",
          alternativeCount: 1,
          conflictCount: 0,
        },
        {
          sectionId: "section_target",
          sectionKey: "target_user",
          title: "타깃 사용자",
          content:
            "초기 타깃은 소규모 팀에서 AI로 서비스 기획, PRD, 기능 명세 초안을 함께 만드는 PM, 디자이너, 개발자다.",
          sortOrder: 3,
          status: "needs_review",
          confidence: 0.72,
          conflictLevel: "medium",
          alternativeCount: 2,
          conflictCount: 1,
        },
        {
          sectionId: "section_features",
          sectionKey: "core_features",
          title: "핵심 기능",
          content:
            "프로젝트 생성, 여러 초안 붙여넣기, AI 병합 분석, 최종 기획서 생성, 섹션별 선택 근거와 다른 의견 확인을 제공한다.",
          sortOrder: 6,
          status: "needs_review",
          confidence: 0.78,
          conflictLevel: "medium",
          alternativeCount: 2,
          conflictCount: 1,
        },
        {
          sectionId: "section_scope",
          sectionKey: "mvp_scope",
          title: "MVP 범위",
          content:
            "초기 MVP는 텍스트 붙여넣기, AI 병합 분석, Hover Preview, 섹션별 비교 패널, 최종 기획서 초안 출력에 집중한다.",
          sortOrder: 7,
          status: "needs_review",
          confidence: 0.81,
          conflictLevel: "high",
          alternativeCount: 3,
          conflictCount: 1,
        },
        {
          sectionId: "section_metrics",
          sectionKey: "success_metrics",
          title: "성공 지표",
          content:
            "병합 시간 감소, 충돌 의견 발견 수, 선택 근거 이해 시간, 최종 기획서 수정 횟수, 다시 사용할 의향을 측정한다.",
          sortOrder: 10,
          status: "auto_selected",
          confidence: 0.84,
          conflictLevel: "none",
          alternativeCount: 1,
          conflictCount: 0,
        },
      ],
    },
    comparisonGroups: [
      {
        id: "group_overview",
        sectionKey: "overview",
        sectionTitle: "개요",
        topic: "서비스 정체성",
        decisionQuestion: "PlanMerge를 기획서 생성기로 볼 것인가, 병합 판단 도구로 볼 것인가?",
        aiConclusion: "병합 판단 도구로 정의하는 것이 적절합니다.",
        keyDifferenceSummary:
          "선택안은 결과물보다 의사결정 과정을 강조하고, 대안은 일반적인 AI 문서 생성기에 가깝습니다.",
        humanDecisionQuestion: "서비스 차별점을 문서 생성에 둘 것인지, 선택 흐름 추적에 둘 것인지 결정해야 합니다.",
        selectedOptionId: "overview_selected",
        needsHumanReview: false,
        conflictLevel: "low",
        confidence: 0.89,
        options: [
          {
            id: "overview_selected",
            optionType: "selected",
            label: "AI 선택안",
            summary: "기획서 초안 병합과 선택 흐름 추적 도구",
            content:
              "여러 AI 초안을 하나로 병합하면서 선택안, 대안, 충돌을 섹션별로 보여준다.",
            differenceFromSelected: "기준 선택안입니다.",
            strengths: ["차별점이 명확하다", "Decision Block 모델과 잘 맞는다"],
            weaknesses: ["처음 설명할 때 약간 낯설 수 있다"],
            scopeImpact: ["병합 리포트", "선택 근거 UI"],
            riskLevel: "low",
            aiRecommendation: "select",
            scores: {
              goalFit: 24,
              userValue: 18,
              mvpFeasibility: 18,
              scopeControl: 14,
              riskReduction: 9,
              validationSpeed: 9,
              total: 92,
            },
            sourceIdeaIds: ["idea_overview_pm"],
            sourceExcerpts: [
              "사용자는 최종안뿐 아니라 왜 선택됐는지, 어떤 의견이 제외됐는지도 확인해야 한다.",
            ],
            conflictsWith: "",
            conflictReason: "",
            decisionQuestion: "",
          },
          {
            id: "overview_alt",
            optionType: "compatible_alternative",
            label: "대안",
            summary: "AI 기획서 자동 작성기",
            content: "사용자 입력을 받아 완성된 기획서를 자동 생성하는 서비스로 포지셔닝한다.",
            differenceFromSelected: "의견 병합보다 문서 생성 자체를 전면에 둔다.",
            strengths: ["사용자가 이해하기 쉽다"],
            weaknesses: ["경쟁 제품과 차별점이 약해진다"],
            scopeImpact: ["생성 품질", "템플릿 관리"],
            riskLevel: "medium",
            aiRecommendation: "defer",
            scores: {
              goalFit: 16,
              userValue: 15,
              mvpFeasibility: 17,
              scopeControl: 13,
              riskReduction: 6,
              validationSpeed: 8,
              total: 75,
            },
            sourceIdeaIds: ["idea_overview_alt"],
            sourceExcerpts: ["최종 기획서 초안을 생성한다."],
            conflictsWith: "",
            conflictReason: "",
            decisionQuestion: "",
          },
        ],
      },
      {
        id: "group_problem",
        sectionKey: "problem",
        sectionTitle: "문제 정의",
        topic: "초안 병합의 어려움",
        decisionQuestion: "주요 문제를 문서 품질 문제로 볼 것인가, 의사결정 추적 문제로 볼 것인가?",
        aiConclusion: "의사결정 추적 문제로 잡는 것이 적절합니다.",
        keyDifferenceSummary:
          "문서 품질보다 어떤 의견이 선택되고 제외됐는지 확인하는 어려움이 더 강한 문제입니다.",
        humanDecisionQuestion: "초기 사용자 인터뷰에서 병합 시간과 선택 근거 이해 중 무엇을 더 우선 측정할지 정해야 합니다.",
        selectedOptionId: "problem_selected",
        needsHumanReview: false,
        conflictLevel: "low",
        confidence: 0.86,
        options: [
          {
            id: "problem_selected",
            optionType: "selected",
            label: "AI 선택안",
            summary: "중복, 충돌, 선택 근거 부재가 문제",
            content:
              "여러 AI 초안이 생기면 최종안보다 선택 과정과 충돌을 파악하는 일이 어려워진다.",
            differenceFromSelected: "기준 선택안입니다.",
            strengths: ["서비스 핵심 UX와 직접 연결된다"],
            weaknesses: ["문제 설명이 추상적으로 보일 수 있다"],
            scopeImpact: ["Decision Block", "출처 추적"],
            riskLevel: "low",
            aiRecommendation: "select",
            scores: {
              goalFit: 23,
              userValue: 18,
              mvpFeasibility: 18,
              scopeControl: 14,
              riskReduction: 8,
              validationSpeed: 9,
              total: 90,
            },
            sourceIdeaIds: ["idea_problem_pm"],
            sourceExcerpts: ["여러 사람이 AI로 기획서를 만들면 중복과 충돌이 생긴다."],
            conflictsWith: "",
            conflictReason: "",
            decisionQuestion: "",
          },
        ],
      },
      {
        id: "group_target",
        sectionKey: "target_user",
        sectionTitle: "타깃 사용자",
        topic: "초기 사용자",
        decisionQuestion: "초기 타깃을 실무 팀으로 할 것인가, 학생 팀 프로젝트로 할 것인가?",
        aiConclusion: "실무에 가까운 소규모 제품팀을 우선 타깃으로 두는 것이 적절합니다.",
        keyDifferenceSummary:
          "실무 팀은 문제 강도가 높고, 학생 팀은 접근성은 좋지만 반복 사용 동기가 약할 수 있습니다.",
        humanDecisionQuestion: "초기 테스트 사용자를 빠르게 확보할 경로가 실무 팀인지 학생 팀인지 결정해야 합니다.",
        selectedOptionId: "target_selected",
        needsHumanReview: true,
        conflictLevel: "medium",
        confidence: 0.72,
        options: [
          {
            id: "target_selected",
            optionType: "selected",
            label: "AI 선택안",
            summary: "소규모 제품팀",
            content: "AI로 서비스 기획, PRD, 기능 명세 초안을 함께 만드는 PM, 디자이너, 개발자",
            differenceFromSelected: "기준 선택안입니다.",
            strengths: ["실제 협업 비용이 크다", "B2B 확장 가능성이 있다"],
            weaknesses: ["초기 리크루팅이 어려울 수 있다"],
            scopeImpact: ["역할 입력", "섹션별 근거 UI"],
            riskLevel: "medium",
            aiRecommendation: "select",
            scores: {
              goalFit: 22,
              userValue: 18,
              mvpFeasibility: 15,
              scopeControl: 12,
              riskReduction: 7,
              validationSpeed: 7,
              total: 81,
            },
            sourceIdeaIds: ["idea_target_pm"],
            sourceExcerpts: ["소규모 팀에서 AI로 서비스 기획, PRD, 기능 명세 초안을 함께 만든다."],
            conflictsWith: "",
            conflictReason: "",
            decisionQuestion: "",
          },
          {
            id: "target_tradeoff",
            optionType: "tradeoff",
            label: "대안",
            summary: "대학생 팀 프로젝트",
            content: "캡스톤, 해커톤, 팀 프로젝트에서 AI 초안을 합치는 대학생 팀",
            differenceFromSelected: "실무팀 대신 접근성이 높은 교육/프로젝트 팀을 타깃으로 한다.",
            strengths: ["인터뷰와 테스트 모집이 쉽다"],
            weaknesses: ["지불 의향과 반복 사용성이 낮을 수 있다"],
            scopeImpact: ["온보딩 문구", "예시 템플릿"],
            riskLevel: "medium",
            aiRecommendation: "needs_human_decision",
            scores: {
              goalFit: 18,
              userValue: 15,
              mvpFeasibility: 18,
              scopeControl: 14,
              riskReduction: 7,
              validationSpeed: 9,
              total: 81,
            },
            sourceIdeaIds: ["idea_target_student"],
            sourceExcerpts: ["초기 테스트 사용자를 확보하기 쉬운 대학생 팀 프로젝트도 가능하다."],
            conflictsWith: "소규모 제품팀",
            conflictReason: "초기 메시지와 검증 지표가 달라진다.",
            decisionQuestion: "실사용 문제 강도와 테스트 접근성 중 무엇을 우선할 것인가?",
          },
        ],
      },
      {
        id: "group_features",
        sectionKey: "core_features",
        sectionTitle: "핵심 기능",
        topic: "비교 인터랙션",
        decisionQuestion: "다른 의견을 오른쪽 패널에서만 볼 것인가, 문서 위 Hover Preview로도 볼 것인가?",
        aiConclusion: "Hover Preview와 오른쪽 상세 패널을 함께 두는 것이 적절합니다.",
        keyDifferenceSummary:
          "Hover Preview는 읽는 흐름을 유지하고, 오른쪽 패널은 깊은 비교와 출처 확인을 맡습니다.",
        humanDecisionQuestion: "첫 데모에서 Hover Preview를 핵심 차별 UX로 보여줄지 결정해야 합니다.",
        selectedOptionId: "feature_selected",
        needsHumanReview: true,
        conflictLevel: "medium",
        confidence: 0.78,
        options: [
          {
            id: "feature_selected",
            optionType: "selected",
            label: "AI 선택안",
            summary: "Hover Preview + 상세 비교 패널",
            content:
              "최종 기획서 위에 커서를 올리면 다른 의견을 팝업으로 보고, 클릭하면 상세 비교 패널에서 분석한다.",
            differenceFromSelected: "기준 선택안입니다.",
            strengths: ["비교 접근성이 높다", "서비스 차별점이 즉시 드러난다"],
            weaknesses: ["상호작용 구현과 모바일 대응이 필요하다"],
            scopeImpact: ["HoverCard", "섹션 상태 마커", "모바일 sheet"],
            riskLevel: "medium",
            aiRecommendation: "select",
            scores: {
              goalFit: 24,
              userValue: 19,
              mvpFeasibility: 15,
              scopeControl: 12,
              riskReduction: 7,
              validationSpeed: 8,
              total: 85,
            },
            sourceIdeaIds: ["idea_hover_designer"],
            sourceExcerpts: [
              "최종 문서를 읽다가 특정 섹션에 커서를 올리면 다른 의견을 바로 볼 수 있어야 한다.",
            ],
            conflictsWith: "",
            conflictReason: "",
            decisionQuestion: "",
          },
          {
            id: "feature_alt_panel",
            optionType: "compatible_alternative",
            label: "대안",
            summary: "오른쪽 패널만 제공",
            content: "섹션 클릭 시 오른쪽 패널에서 선택 근거와 대안을 본다.",
            differenceFromSelected: "문서 위 즉시 미리보기 없이 클릭 기반 탐색만 제공한다.",
            strengths: ["구현이 단순하다", "정보 밀도 관리가 쉽다"],
            weaknesses: ["다른 의견 존재를 놓칠 수 있다"],
            scopeImpact: ["Side Panel"],
            riskLevel: "low",
            aiRecommendation: "keep_as_alternative",
            scores: {
              goalFit: 19,
              userValue: 15,
              mvpFeasibility: 19,
              scopeControl: 15,
              riskReduction: 8,
              validationSpeed: 9,
              total: 85,
            },
            sourceIdeaIds: ["idea_panel"],
            sourceExcerpts: ["섹션 클릭 시 우측 패널 표시"],
            conflictsWith: "",
            conflictReason: "",
            decisionQuestion: "",
          },
        ],
      },
      {
        id: "group_scope",
        sectionKey: "mvp_scope",
        sectionTitle: "MVP 범위",
        topic: "초기 기능 범위",
        decisionQuestion: "초기 MVP에 외부 연동과 실시간 협업을 포함할 것인가?",
        aiConclusion: "포함하지 않고 붙여넣기 기반 병합과 비교 UX 검증에 집중하는 것이 적절합니다.",
        keyDifferenceSummary:
          "선택안은 병합 판단 검증에 집중하고, 다른 의견들은 문서 연동이나 협업 워크스페이스로 범위를 넓힙니다.",
        humanDecisionQuestion: "이번 MVP의 목적은 AI 병합 판단 검증인가, 협업 워크스페이스 검증인가?",
        selectedOptionId: "scope_selected",
        needsHumanReview: true,
        conflictLevel: "high",
        confidence: 0.81,
        options: [
          {
            id: "scope_selected",
            optionType: "selected",
            label: "AI 선택안",
            summary: "붙여넣기 기반 병합 + 비교 UX",
            content:
              "텍스트 붙여넣기, AI 분석, Hover Preview, 섹션별 비교 패널, 최종 기획서 초안 출력에 집중한다.",
            differenceFromSelected: "기준 선택안입니다.",
            strengths: ["2주 MVP에 적합하다", "핵심 가치를 직접 검증한다", "기술 리스크가 낮다"],
            weaknesses: ["외부 업무 도구와의 연결성은 부족하다"],
            scopeImpact: ["단일 페이지 입력", "OpenAI 분석 API", "비교 UI"],
            riskLevel: "low",
            aiRecommendation: "select",
            scores: {
              goalFit: 25,
              userValue: 18,
              mvpFeasibility: 20,
              scopeControl: 15,
              riskReduction: 10,
              validationSpeed: 10,
              total: 98,
            },
            sourceIdeaIds: ["idea_scope_pm", "idea_scope_dev"],
            sourceExcerpts: [
              "초기 MVP는 텍스트 붙여넣기와 병합 리포트 생성까지만 포함해야 한다.",
              "2주 MVP에서는 위험하다.",
            ],
            conflictsWith: "",
            conflictReason: "",
            decisionQuestion: "",
          },
          {
            id: "scope_alt_notion",
            optionType: "compatible_alternative",
            label: "대안 A",
            summary: "Notion 내보내기 포함",
            content: "최종 기획서를 Notion으로 내보내는 기능을 초기 MVP에 포함한다.",
            differenceFromSelected: "외부 문서 도구 연동이 초기 범위에 들어간다.",
            strengths: ["실제 팀 업무 흐름에 가깝다", "결과물 활용성이 높다"],
            weaknesses: ["인증, API 예외 처리, 포맷 변환이 필요하다"],
            scopeImpact: ["Notion API", "OAuth 또는 토큰 관리", "문서 포맷 변환"],
            riskLevel: "medium",
            aiRecommendation: "defer",
            scores: {
              goalFit: 17,
              userValue: 16,
              mvpFeasibility: 9,
              scopeControl: 7,
              riskReduction: 4,
              validationSpeed: 5,
              total: 58,
            },
            sourceIdeaIds: ["idea_scope_notion"],
            sourceExcerpts: ["Notion으로 내보내거나 Slack에 공유하면 실제 팀 업무 흐름에 더 가까울 수 있다."],
            conflictsWith: "",
            conflictReason: "",
            decisionQuestion: "",
          },
          {
            id: "scope_alt_slack",
            optionType: "compatible_alternative",
            label: "대안 B",
            summary: "Slack 공유 포함",
            content: "병합 결과와 충돌 의견을 Slack으로 공유한다.",
            differenceFromSelected: "분석 결과 이후의 팀 공유 기능이 초기 범위에 들어간다.",
            strengths: ["팀 알림과 공유가 쉬워진다"],
            weaknesses: ["핵심 병합 검증과 직접 관련은 약하다"],
            scopeImpact: ["Slack API", "공유 메시지 템플릿"],
            riskLevel: "medium",
            aiRecommendation: "defer",
            scores: {
              goalFit: 15,
              userValue: 14,
              mvpFeasibility: 10,
              scopeControl: 8,
              riskReduction: 5,
              validationSpeed: 5,
              total: 57,
            },
            sourceIdeaIds: ["idea_scope_slack"],
            sourceExcerpts: ["Slack에 공유하면 실제 팀 업무 흐름에 더 가까울 수 있다."],
            conflictsWith: "",
            conflictReason: "",
            decisionQuestion: "",
          },
          {
            id: "scope_conflict_realtime",
            optionType: "direct_conflict",
            label: "충돌 의견",
            summary: "실시간 공동 편집 포함",
            content: "초기 MVP부터 여러 사용자가 동시에 문서를 편집하는 기능을 제공한다.",
            differenceFromSelected: "단일 페이지 병합 도구에서 협업 문서 편집 도구로 성격이 바뀐다.",
            strengths: ["협업 제품으로 보일 수 있다"],
            weaknesses: ["팀 초대, 권한, 동기화, 충돌 해결이 필요하다"],
            scopeImpact: ["인증", "권한 관리", "실시간 동기화", "동시 편집 충돌 처리"],
            riskLevel: "high",
            aiRecommendation: "reject_for_mvp",
            scores: {
              goalFit: 10,
              userValue: 18,
              mvpFeasibility: 3,
              scopeControl: 2,
              riskReduction: 1,
              validationSpeed: 2,
              total: 36,
            },
            sourceIdeaIds: ["idea_scope_realtime"],
            sourceExcerpts: ["실시간 공동 편집을 넣으면 팀 초대, 권한, 동기화, 충돌 해결까지 필요하다."],
            conflictsWith: "붙여넣기 기반 병합 + 비교 UX",
            conflictReason:
              "현재 선택안은 AI 병합 판단 검증을 위한 단일 페이지 MVP인데, 실시간 공동 편집은 협업 워크스페이스 범위를 요구한다.",
            decisionQuestion: "AI 병합 판단을 먼저 검증할 것인가, 실시간 협업 경험을 먼저 검증할 것인가?",
          },
        ],
      },
      {
        id: "group_metrics",
        sectionKey: "success_metrics",
        sectionTitle: "성공 지표",
        topic: "검증 기준",
        decisionQuestion: "성공 지표를 문서 완성도 중심으로 볼 것인가, 비교 이해도 중심으로 볼 것인가?",
        aiConclusion: "비교 이해도와 충돌 발견을 핵심 지표로 두는 것이 적절합니다.",
        keyDifferenceSummary:
          "PlanMerge의 차별점은 문서를 더 빨리 쓰는 것보다 다른 의견을 이해하고 결정하는 속도에 있습니다.",
        humanDecisionQuestion: "첫 테스트에서 어떤 행동 로그를 꼭 남길지 정해야 합니다.",
        selectedOptionId: "metrics_selected",
        needsHumanReview: false,
        conflictLevel: "none",
        confidence: 0.84,
        options: [
          {
            id: "metrics_selected",
            optionType: "selected",
            label: "AI 선택안",
            summary: "병합 시간, 충돌 발견, 선택 근거 이해도",
            content:
              "사용자가 여러 AI 초안을 넣은 뒤 다른 의견과 선택 근거를 얼마나 빨리 이해하는지 측정한다.",
            differenceFromSelected: "기준 선택안입니다.",
            strengths: ["핵심 가치와 직접 연결된다"],
            weaknesses: ["정성 평가가 일부 필요하다"],
            scopeImpact: ["분석 완료 시간", "섹션 클릭/hover 로그"],
            riskLevel: "low",
            aiRecommendation: "select",
            scores: {
              goalFit: 23,
              userValue: 17,
              mvpFeasibility: 18,
              scopeControl: 14,
              riskReduction: 8,
              validationSpeed: 9,
              total: 89,
            },
            sourceIdeaIds: ["idea_metrics"],
            sourceExcerpts: [
              "병합 시간 감소, 충돌 의견 발견 수, 선택 근거 이해 시간, 최종 기획서 수정 횟수, 다시 사용할 의향을 측정한다.",
            ],
            conflictsWith: "",
            conflictReason: "",
            decisionQuestion: "",
          },
        ],
      },
    ],
    usedMock: true,
  };

  return {
    ...response,
    ...input,
  };
}
