export const planMergeAnalysisJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: ["summary", "finalDocument", "comparisonGroups"],
  properties: {
    summary: {
      type: "object",
      additionalProperties: false,
      required: [
        "text",
        "sectionCount",
        "autoSelectedCount",
        "needsReviewCount",
        "conflictCount",
        "overallRiskLevel",
      ],
      properties: {
        text: { type: "string" },
        sectionCount: { type: "integer" },
        autoSelectedCount: { type: "integer" },
        needsReviewCount: { type: "integer" },
        conflictCount: { type: "integer" },
        overallRiskLevel: { type: "string", enum: ["low", "medium", "high"] },
      },
    },
    finalDocument: {
      type: "object",
      additionalProperties: false,
      required: ["title", "sections"],
      properties: {
        title: { type: "string" },
        sections: {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            required: [
              "sectionId",
              "sectionKey",
              "title",
              "content",
              "sortOrder",
              "status",
              "confidence",
              "conflictLevel",
              "alternativeCount",
              "conflictCount",
            ],
            properties: {
              sectionId: { type: "string" },
              sectionKey: { type: "string" },
              title: { type: "string" },
              content: { type: "string" },
              sortOrder: { type: "integer" },
              status: {
                type: "string",
                enum: ["auto_selected", "needs_review", "approved", "overridden"],
              },
              confidence: { type: "number" },
              conflictLevel: {
                type: "string",
                enum: ["none", "low", "medium", "high"],
              },
              alternativeCount: { type: "integer" },
              conflictCount: { type: "integer" },
            },
          },
        },
      },
    },
    comparisonGroups: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "sectionKey",
          "sectionTitle",
          "topic",
          "decisionQuestion",
          "aiConclusion",
          "keyDifferenceSummary",
          "humanDecisionQuestion",
          "selectedOptionId",
          "needsHumanReview",
          "conflictLevel",
          "confidence",
          "options",
        ],
        properties: {
          id: { type: "string" },
          sectionKey: { type: "string" },
          sectionTitle: { type: "string" },
          topic: { type: "string" },
          decisionQuestion: { type: "string" },
          aiConclusion: { type: "string" },
          keyDifferenceSummary: { type: "string" },
          humanDecisionQuestion: { type: "string" },
          selectedOptionId: { type: "string" },
          needsHumanReview: { type: "boolean" },
          conflictLevel: {
            type: "string",
            enum: ["none", "low", "medium", "high"],
          },
          confidence: { type: "number" },
          options: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              required: [
                "id",
                "optionType",
                "label",
                "summary",
                "content",
                "differenceFromSelected",
                "strengths",
                "weaknesses",
                "scopeImpact",
                "riskLevel",
                "aiRecommendation",
                "scores",
                "sourceIdeaIds",
                "sourceExcerpts",
                "conflictsWith",
                "conflictReason",
                "decisionQuestion",
              ],
              properties: {
                id: { type: "string" },
                optionType: {
                  type: "string",
                  enum: [
                    "selected",
                    "same_direction",
                    "compatible_alternative",
                    "tradeoff",
                    "direct_conflict",
                    "out_of_scope",
                  ],
                },
                label: { type: "string" },
                summary: { type: "string" },
                content: { type: "string" },
                differenceFromSelected: { type: "string" },
                strengths: { type: "array", items: { type: "string" } },
                weaknesses: { type: "array", items: { type: "string" } },
                scopeImpact: { type: "array", items: { type: "string" } },
                riskLevel: { type: "string", enum: ["low", "medium", "high"] },
                aiRecommendation: {
                  type: "string",
                  enum: [
                    "select",
                    "keep_as_alternative",
                    "defer",
                    "reject_for_mvp",
                    "needs_human_decision",
                  ],
                },
                scores: {
                  type: "object",
                  additionalProperties: false,
                  required: [
                    "goalFit",
                    "userValue",
                    "mvpFeasibility",
                    "scopeControl",
                    "riskReduction",
                    "validationSpeed",
                    "total",
                  ],
                  properties: {
                    goalFit: { type: "integer" },
                    userValue: { type: "integer" },
                    mvpFeasibility: { type: "integer" },
                    scopeControl: { type: "integer" },
                    riskReduction: { type: "integer" },
                    validationSpeed: { type: "integer" },
                    total: { type: "integer" },
                  },
                },
                sourceIdeaIds: { type: "array", items: { type: "string" } },
                sourceExcerpts: { type: "array", items: { type: "string" } },
                conflictsWith: { type: "string" },
                conflictReason: { type: "string" },
                decisionQuestion: { type: "string" },
              },
            },
          },
        },
      },
    },
  },
} as const;
